# Uncomment the next line to define a global platform for your project
  platform:ios, '10.0'

target 'AgoraBuilder' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Armin', '1.1.0'
  pod 'SwifterSwift', '5.2.0'
  pod 'Masonry', '1.1.0'

  # Netless
  pod 'Whiteboard', '2.16.45'
  
  # Hyphenate
  pod 'Agora_Chat_iOS', '1.0.6'
  pod 'SDWebImage', '<=5.12.0'
  pod 'AgoraLog','1.0.2'

  #open
  pod 'AgoraWidgets/Source', :path => '../../AgoraWidgets_Local.podspec'

  #close
  pod 'AgoraWidget/Binary', :path => '../../../apaas-common-libs-ios/AgoraWidget_Local.podspec'
  pod 'AgoraUIBaseViews/Binary', :path => '../../../apaas-common-libs-ios/AgoraUIBaseViews_Local.podspec'  
  
  post_install do |installer|
     installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['BITCODE_GENERATION_MODE'] = 'bitcode'
          config.build_settings['ENABLE_BITCODE'] = 'YES'
        end
     end
  end
end
